import { CounselorGroup } from "../models/CounselorGroup.js";
import { sendEmail } from "../services/email.service.js";
import { marked } from "marked"; // 1. Import marked

/**
 * Defines the job logic for sending post-meeting summaries.
 * @param {import("agenda").Agenda} agenda - The Agenda instance
 */
export const defineSummaryAgent = (agenda) => {
  agenda.define("send-summary-email", async (job) => {
    const { meetingCode, summaryText, counselorName } = job.attrs.data;
    console.log(
      `[SummaryAgent] Processing summary email for room code: ${meetingCode}`,
    );

    try {
      let group = await CounselorGroup.findOne({
        dedicatedMeetingCode: meetingCode,
      }).populate("devotees", "name username");

      if (!group && counselorName) {
        group = await CounselorGroup.findOne({
          counselorName: counselorName,
        }).populate("devotees", "name username");
      }

      if (!group) {
        console.warn(
          `[SummaryAgent] No counselor group found for code: ${meetingCode}. Aborting.`,
        );
        return;
      }

      const devoteeEmails = group.devotees
        ?.map((d) => d.username)
        .filter(Boolean);

      if (!devoteeEmails || devoteeEmails.length === 0) {
        console.log(
          `[SummaryAgent] No registered devotees found for this counselor. Aborting email.`,
        );
        return;
      }

      console.log(
        `[SummaryAgent] Sending summary to ${devoteeEmails.length} devotees via BCC.`,
      );

      // 2. Convert the raw markdown from Gemini into formatted HTML
      const formattedHtmlSummary = marked.parse(summaryText);

      await sendEmail({
        to: process.env.EMAIL_USER,
        bcc: devoteeEmails,
        subject: `Session Summary: ${group.counselorName}'s Class`,
        text: `Hare Krishna!\n\nHere is the summary of today's session with ${group.counselorName}:\n\n${summaryText}`, // Keep raw text for plain-text fallback
        html: `
          <div style="font-family: Arial, sans-serif; padding: 20px; line-height: 1.6; color: #333;">
            <h2 style="color: #2c3e50;">Hare Krishna! 🙏</h2>
            <p>Here are the discussion notes and summary from the recent session with <b>${group.counselorName}</b>:</p>
            <hr style="border: 1px solid #eee; margin: 20px 0;"/>
            
            <!-- 3. Inject the parsed HTML here inside a styled div instead of a pre tag -->
            <div style="background: #f9f9f9; padding: 20px; border-radius: 8px; border: 1px solid #e5e7eb; font-size: 15px;">
              ${formattedHtmlSummary}
            </div>
            
            <p style="margin-top: 20px; font-size: 12px; color: #888;">This is an automated summary generated by VaniLink AI.</p>
          </div>
        `,
      });

      console.log(`[SummaryAgent] Summary email successfully dispatched.`);
    } catch (error) {
      console.error(
        `[SummaryAgent] Critical error processing summary job:`,
        error,
      );
      throw error;
    }
  });
};
